### ISSUE TITLE
request for melodic release

### ISSUE THREAD

**Issue by k-okada** [ros-perception/camera_info_manager_py#12]
@jack-oquin Can you release camera_info_manager_py into meldoic?  I am about to release axis_camera on melodic and noticed it depends on this.

https://travis-ci.com/ros-drivers/axis_camera/jobs/155713653

**Comment by jordy-van-appeven** [comment]
I would also like to request the maintainer(s) for a package release in melodic.

**Comment by k-okada** [comment]
if no one can release this to melodic, can someone @jack-oquin @wjwwood ?
@dirk-thomas ? give me write access to this repository and
https://github.com/ros-gbp/camera_info_manager_py-release so that I can release as a ROS
[Ophaned Package Maintainer](http://wiki.ros.org/OrphanedPackag) ?

**Comment by abviv** [comment]
@k-okada  were you granted the write access to the upstream?

**Comment by k-okada** [comment]
@abviv unfortunately not

**Comment by abviv** [comment]
@wjwwood @dirk-thomas have you guys planned for the melodic release? Any updates would be great!

**Comment by dirk-thomas** [comment]
I just did a one-time release into Melodic: ros/rosdistro#23048

Let me know if you need any further access for future work.

**Comment by k-okada** [comment]
@dirk-thomas thank you, yes if no one interested in maintain / releasing this package, http://wiki.ros.org/OrphanedPackage  / https://github.com/ros-infrastructure/rep/pull/150  will take care about that
